name: Build SMAPI-Android

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Merge and Extract Dependencies
      run: |
        cd src/DependenciesDll
        cat libs.zip.* > libs.zip
        unzip -o libs.zip -d .
        rm libs.zip

    - name: Build with dotnet
      run: |
        dotnet build -c Release
