name: Build Patcher DLL

on:
  push:
    branches: [ develop, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build SMAPI Project
        run: dotnet build ./src/SMAPI/SMAPI.csproj -c Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AndroidPatcher-DLL
          path: '**/StardewModdingAPI.Mobile.AndroidPatcher.dll'
