name: Build Patcher DLL

on:
  push:
    branches: [ develop, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Dependencies
        run: |
          mkdir -p ./src/DependenciesDll
          ARCHIVE=$(find . -maxdepth 4 -type f \( -name "*.7z" -o -name "*.zip" -o -name "*libs*" \) | head -n 1)
          echo "Found file at: $ARCHIVE"
          7z x "$ARCHIVE" -o./src/DependenciesDll/ -y

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Android Workload
        run: dotnet workload install android

      - name: Build SMAPI Project
        run: dotnet build ./src/SMAPI/SMAPI.csproj -c Release /p:GamePath="../DependenciesDll"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AndroidPatcher-DLL
          path: '**/StardewModdingAPI.Mobile.AndroidPatcher.dll'
